### ISSUE TITLE
Are ready messages essential?

### ISSUE THREAD

**Issue by jstuyts** [FUDCo/Elko#2]
I have created a fork [jstuyts/Elko](https://github.com/jstuyts/Elko), and I am currently working on getting the chat working (not pushed yet). I get errors that objects do not handle the `ready` message.

Are the `ready` messages essential for correctly working applications? If so, can you give an example what a context or user object should/can do when it receives this message.

**Comment by FUDCo** [comment]
The `ready` message informs the client of the completion of a series of messages that describe a new context or new user entering a context.  Whether it is necessary or not for the client to actually handle the message depends on the nature of the application -- simple applications that just take things as they come may not need it, but anything that cares about knowing whether it has a complete, self consistent description of an object will want to pay attention to the message.  If you don't care, it should be easy enough to have your client's handler for the message be a no-op.

I hope that clears things up, but feel free to ask more probing questions if not.

**Comment by jstuyts** [comment]
Right, so in the case of chats, if I do not want the user to be able to send messages before everything in the chat room and all items belonging to the user are known, I have to wait for the ready messages.

Thanks.
